//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interface_RATP.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GER {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GER() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Interface_RATP.Ressources.GER", typeof(GER).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zurück.
        /// </summary>
        internal static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erwachsener.
        /// </summary>
        internal static string lblAdult {
            get {
                return ResourceManager.GetString("lblAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flughafen.
        /// </summary>
        internal static string lblAirport {
            get {
                return ResourceManager.GetString("lblAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à aktuelle Summe.
        /// </summary>
        internal static string lblCurrentPriceText {
            get {
                return ResourceManager.GetString("lblCurrentPriceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erwachsenser.
        /// </summary>
        internal static string lblDisneyAdult {
            get {
                return ResourceManager.GetString("lblDisneyAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kind.
        /// </summary>
        internal static string lblDisneyChild {
            get {
                return ResourceManager.GetString("lblDisneyChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Normale Tickets.
        /// </summary>
        internal static string lblNormalTickets {
            get {
                return ResourceManager.GetString("lblNormalTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Besuchspass 1 Tag.
        /// </summary>
        internal static string lblParis1 {
            get {
                return ResourceManager.GetString("lblParis1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Besuchspass 3 Tage.
        /// </summary>
        internal static string lblParis3 {
            get {
                return ResourceManager.GetString("lblParis3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Besuchspass 5 Tage.
        /// </summary>
        internal static string lblParis5 {
            get {
                return ResourceManager.GetString("lblParis5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à reduzierter Preis.
        /// </summary>
        internal static string lblReduction {
            get {
                return ResourceManager.GetString("lblReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sondertickets.
        /// </summary>
        internal static string lblSpecialTickets {
            get {
                return ResourceManager.GetString("lblSpecialTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Danke !.
        /// </summary>
        internal static string lblThanks {
            get {
                return ResourceManager.GetString("lblThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tickets.
        /// </summary>
        internal static string lblTickets {
            get {
                return ResourceManager.GetString("lblTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gesamt.
        /// </summary>
        internal static string lblTotal {
            get {
                return ResourceManager.GetString("lblTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wilkommen am RATP.
        /// </summary>
        internal static string lblWelcome {
            get {
                return ResourceManager.GetString("lblWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Normale Tickets.
        /// </summary>
        internal static string MessageBox1Caption {
            get {
                return ResourceManager.GetString("MessageBox1Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Normale Tickets beinhalten die Optionen: Erwachsener und ermäßigter Preis.
        /// </summary>
        internal static string MessageBox1Text {
            get {
                return ResourceManager.GetString("MessageBox1Text", resourceCulture);
            }
        }
    }
}
